export const actionType = {
  ADD_TO_CART: "ADD_TO_CART",
  ADJUST_QTY: "ADJUST_QTY",
  REMOVE_ITEM : "REMOVE_ITEM",
  LOAD_ALL_PRODUCT: "LOAD_ALL_PRODUCT",
  LOAD_SINGLE_PRODUCT: "LOAD_SINGLE_PRODUCT"
}